Add script to download canvas submission data
HCI-Data-Analysis/HCI-data-analysis pull request #16
Opened 2021-09-23 20:04 UTC by MtheDV

Closes #15

2021-09-23 20:22 UTC, carson-ricca approved these changes
Looks good to me, if it's been tested and does what is expected with the submissions then it should be good to merge.

2021-09-23 21:19 UTC, carson-ricca submitted a review, later dismissed

2021-09-26 06:46 UTC, Opeyem1a requested changes

2021-09-26 06:46 UTC, Opeyem1a commented on scripts/canvas_submission_retrieval/canvas_submission_retrieval.md
> +# Download Course Submission Data v1
I feel like our .md files are so in depth and they don't need to be - take a look at #18 and see the updated .md files for each script. There's no need to document file structure since again, we should just explain the goals of the script in plain english

2021-09-26 06:46 UTC, Opeyem1a commented on scripts/canvas_submission_retrieval/canvas_submission_retrieval.py
> +        with open(f"../../data/{course_id}_{assignment.id}.json", "w") as f:
this directory path (`../../data/`) should be a parameter of this function. We run these files from entrypoint files located elsewhere in the project, so relative pathing doesn't work consistently like this

2021-09-26 06:46 UTC, Opeyem1a commented on scripts/canvas_submission_retrieval/canvas_submission_retrieval.py
> +if __name__ == '__main__':
I think it'd be best to make an entrypoint file in the root directory that calls this method instead of using the `if __name__ == '__main__':` pattern here

2021-09-30 20:51 UTC, Opeyem1a requested changes

2021-09-30 20:51 UTC, Opeyem1a commented on submission_retrieval.py
> +    encoder = Encoder(key_path)
we shouldn't generate a key in this script, so for now make a constant that hardcodes the path to `keys/Key,csv` and just pass that directly into the encoder

2021-09-30 20:51 UTC, Opeyem1a commented on submission_retrieval.py
> +EXPORT_DIR = os.path.join('data', 'canvas_submission')
if you're just setting this to a constant, doing this is equivalent to hardcoding

2021-09-30 20:51 UTC, Opeyem1a commented on submission_retrieval.py
> +CANVAS_COURSE_ID = sys.argv[2]
Add a section in the README to explain exactly how to call this script (we'll figure out better solutions later)
Something like "Run `python canvas_submission_retrieval <ACCESS_TOKEN> <COURSE_ID>`"

2021-09-30 21:06 UTC, Rick-Feng-u commented on submission_retrieval.py
> +EXPORT_DIR = os.path.join('data', 'canvas_submission')
EXPORT_DIR is supposed to be a hardcoded path. We decided to use os.path.join is because we could easily add more directories in if it is required.

2021-10-01 04:02 UTC, Opeyem1a submitted a review, later dismissed

2021-10-01 04:18 UTC, aadiraju submitted a review, later dismissed
Looks fine. I think we need to think about how we can avoid hardcoding paths for our files into each script, and maybe export the variables so there is only one global pathset. Specifically, I mean the `KEY_PATH`

2021-10-01 04:21 UTC, Rick-Feng-u commented
> Looks fine. I think we need to think about how we can avoid hardcoding paths for our files into each script, and maybe export the variables so there is only one global pathset. Specifically, I mean the `KEY_PATH`

Maybe we should consider env files?

2021-10-01 13:55 UTC, Opeyem1a commented
We'll be adding .env files in a PR coming in soon 👍

2021-10-05 09:31 UTC, Opeyem1a approved these changes

2021-10-05 09:32 UTC, merged