Student Group Clustering
HCI-Data-Analysis/HCI-data-analysis pull request #19
Opened 2021-09-28 17:17 UTC by carson-ricca

- Implementation of the student group clustering.
- Multiple KMeans runs will be a separate pull request.

2021-09-28 21:19 UTC, aadiraju commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +        answers = row[2].split(",")
Is there a way to do this with column names/schemas? I think it might be nice for code clarity/readability

2021-09-28 21:19 UTC, aadiraju commented on scripts/clustering/background_survey_clustering/background_survey_clustering.py
> +# plt.show()
If this isn't needed please remove it.

2021-09-28 21:19 UTC, aadiraju commented on scripts/clustering/background_survey_clustering/background_survey_clustering.py
> +# plt.show()
or mention a reason to leave it in as a comment above it

2021-09-28 21:19 UTC, aadiraju commented on scripts/clustering/clustering_model.py
> +# data = pd.read_csv(DataFilesSchema.BACKGROUND_CLUSTER_DATA)
Remove if not needed

2021-09-28 21:19 UTC, aadiraju commented on scripts/clustering/data_preparation_for_clustering.py
> +    negatives_col_nums = schema["col num 1"][schema["positive/negative"] < 1]
wait will it always have a column called `"col num 1"` ?

2021-09-28 21:19 UTC, aadiraju commented on scripts/clustering/data_preparation_for_clustering.py
> +    result = pd.concat([student_info.reset_index(drop=True), aggregate.reset_index(drop=True)], axis=1)
Is there some way to do this without indices? I can't actually tell what you are dropping without an explanation.

2021-09-28 21:58 UTC, carson-ricca commented on scripts/clustering/clustering_model.py
> +# data = pd.read_csv(DataFilesSchema.BACKGROUND_CLUSTER_DATA)
This one will be used can remain for now.

2021-09-28 21:59 UTC, carson-ricca commented on scripts/clustering/data_preparation_for_clustering.py
> +    result = pd.concat([student_info.reset_index(drop=True), aggregate.reset_index(drop=True)], axis=1)
It could but then it would involve a large amount of id's which I found to be fairly unreadable. I believe the `md` should mention what fields are dropped. If not this can be updated.

2021-09-28 21:59 UTC, carson-ricca commented on scripts/clustering/data_preparation_for_clustering.py
> +    negatives_col_nums = schema["col num 1"][schema["positive/negative"] < 1]
The schema always does yes.

2021-09-28 22:00 UTC, carson-ricca commented on scripts/clustering/background_survey_clustering/background_survey_clustering.py
> +# plt.show()
Yes this can be removed.

2021-09-28 22:00 UTC, carson-ricca commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +        answers = row[2].split(",")
The column name is like 100 lines of string basically lol

2021-09-29 05:41 UTC, Opeyem1a requested changes

2021-09-29 05:41 UTC, Opeyem1a commented on schemas/data_files.py
> +class DataFilesSchema:
As a general thing, I think it's best if every major thing we do is accessed through entrypoint `.py` files in the root directory (like how anaonymize.py calls the functions from the `/scripts` files).

This way, we can just have file paths like this be constants in an entrypoint file like `cluster_impressions.py` or `cluster_personality.py`. The benefits I see with this are:
a) calling `python cluster_impressions.py` is easier than calling multiple files to complete the task
b) the `cluster_impressions.py` file would already call any needed functions in the correct order
c) the code can be more reusable if functions use more parameters (*we can talk more in detail about what I mean by this)

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +def prepare_df():
Since this function does such a specific thing, I think we should name it more specifically, too

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +    df = pd.read_csv(DataFilesSchema.BACKGROUND_SURVEY_DATA)
From my larger comment about entrypoint files, I think file locations, in general, should be parameters so that files within the `/scripts` folder don't need to have file locations typed into them (even if it's with a constant like this one)

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +def export_to_csv(df):
Do we need this function? It's only used once and doesn't really change the functionality of `DataFrame.to_csv()`. If we do keep it because we add more functionality to it, then we need to either make it more generalizable or rename the function to be more specific

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +def get_columns(questions):
For functions like this that have generic names but are only used in this context, we could name them like `_get_columns()` which implies, for python, that this function is only used in this file or class

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +def map_to_number(answer):
`_map_to_number()`

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +        return 0
it seems dangerous to have this default case here. What if we did it like
```
ANSWER_OPTIONS = {
'Strongly Disagree': -2,
'Disagree': -1,
...
'Strongly Agree': 2,
}
return ANSWER_OPTIONS[answer]
```

This way if the answer is not one of the options it just errors and we'll know

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/clustering_model.py
> +def export_to_csv(file_path):
We have multiple functions called `export_to_csv()` that do the same thing? Does this one need to be a function either?

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/data_preparation_for_clustering.py
> +def map_to_number(survey):
We have 2 `map_to_number()` functions - Why does this one work differently to the other? Can it be generalized?

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/data_preparation_for_clustering.py
> +    negatives_col_nums = schema["col num 1"][schema["positive/negative"] < 1]
The goal of `/schemas` is to avoid using string literals to refer to column names in the code when possible. So we would have `/schema`s for each csv you create and changing "col name 1" to "more descriptive name" would only be a change in the `/schemas` folder

2021-09-29 05:41 UTC, Opeyem1a commented on scripts/clustering/data_preparation_for_clustering.py
> +def export_to_csv(df, survey_path):
This function feels different to the other `export_to_csv()`, it could be named more specifically to its purpose since it adds functionality beyond just exporting to csv

2021-09-29 18:32 UTC, carson-ricca commented on scripts/clustering/clustering_model.py
> +    # pair_plot()
@Opeyem1a This will need to be discussed where these functions are supposed to be called.

2021-09-29 21:33 UTC, Opeyem1a commented on scripts/clustering/data_preparation_for_clustering.py
> +def map_to_number(survey):
Goal is to keep this `map_to_number()` function

2021-09-29 21:33 UTC, Opeyem1a commented on cluster_background.py
> +BACKGROUND_SURVEY_SCHEMA = "../../../data/processed/background_survey_schema.csv"
update file paths

2021-09-29 21:33 UTC, Opeyem1a commented on cluster_background.py
> +from scripts.clustering.background_survey_cleaning.background_survey_cleaning import clean_background_survey
update __init__.py

2021-09-29 21:33 UTC, Opeyem1a commented on scripts/clustering/clustering_model.py
> +def pair_plot(labeled_data):
doesn't need a function

2021-09-29 21:33 UTC, Opeyem1a commented on scripts/clustering/clustering_model.py
> +    # pair_plot()
Inertia Graph: one of the functions to determine how many clusters we choose.
- cluster_data: dataframe of independent variables (for_clustering_[something]_survey.csv without index column)
- k: number (for now, 10)

Pair Plot
- comment on that piece of code

2021-09-30 20:41 UTC, Opeyem1a commented on cluster_impressions.py
> +    prepare_data_for_clustering(HCI_SURVEY_DATA, HCI_SURVEY_SCHEMA, OUTPUT_DIRECTORY)
I got
```
Traceback (most recent call last):
  File "D:\School\DATA 448\HCI-data-analysis\cluster_impressions.py", line 14, in <module>
    cluster_survey(HCI_CLUSTER_DATA, STUDENT_GROUP_OUTPUT_DIRECTORY)
  File "D:\School\DATA 448\HCI-data-analysis\scripts\clustering\clustering_model.py", line 12, in cluster_survey
    get_groups(kmeans_clustering(3, cluster_data), data).to_csv(output_path_filename)
  File "D:\School\DATA 448\HCI-data-analysis\util\cluster.py", line 36, in kmeans_clustering
    kmeans = KMeans(n_clusters=n_clusters).fit(cluster_data)
  File "D:\School\DATA 448\HCI-data-analysis\venv\lib\site-packages\sklearn\cluster\_kmeans.py", line 1148, in fit
    self._check_params(X)
  File "D:\School\DATA 448\HCI-data-analysis\venv\lib\site-packages\sklearn\cluster\_kmeans.py", line 949, in _check_params
    raise ValueError(
ValueError: n_samples=1 should be >= n_clusters=3.
```

2021-09-30 20:41 UTC, Opeyem1a commented on util/cluster.py
> +    labeled_data = pd.concat((cluster_data, labels), axis=1)
`labeled_data` is no longer used

2021-10-01 18:50 UTC, nononovia commented on util/cluster.py
> +    labeled_data = pd.concat((cluster_data, labels), axis=1)
The function kmeans_clustering() should return labeled_data instead. Thank you for pointing it out

2021-10-02 19:11 UTC, carson-ricca commented on cluster_impressions.py
> +    prepare_data_for_clustering(HCI_SURVEY_DATA, HCI_SURVEY_SCHEMA, OUTPUT_DIRECTORY)
Could not replicate this issue when I ran it.

2021-10-02 22:49 UTC, Opeyem1a approved these changes

2021-10-02 22:49 UTC, merged