fix the bug that causes the buggy row in background_ground_survey_cle…
HCI-Data-Analysis/HCI-data-analysis pull request #42
Opened 2021-10-25 03:08 UTC by nononovia

…aning.py

2021-10-31 01:32 UTC, nononovia commented on data/processed/processed_background_survey.csv
> -id,"3430866: Below are a number of personality characteristics. For each characteristic, please write to what extent you agree or disagree with it.
processed_background_survey may not be needed in clustering salvage but it is still required to generate the average answer for each question category which is used for the "manual" group generation?

2021-10-31 01:33 UTC, nononovia commented on data/student_group/for_clustering_processed_background_survey.csv
> -,g1,g0,g2
Same situation to above as well.

2021-10-31 02:01 UTC, nononovia commented on cluster_background.py
> +    # prepare_data_for_clustering(PROCESSED_BACKGROUND_SURVEY_DATA, BACKGROUND_SURVEY_SCHEMA, OUTPUT_DIRECTORY)
File changed completely, through Carson's clustering salvage, therefore resolved

2021-10-31 02:02 UTC, nononovia commented on cluster_background.py
> +    # cluster_survey(BACKGROUND_CLUSTER_DATA, STUDENT_GROUP_OUTPUT_DIRECTORY, CLUSTER_CATEGORIES)
Merged main into this branch to ensure these files are up to date.

2021-10-31 02:04 UTC, nononovia commented on data/processed/processed_background_survey.csv
> -id,"3430866: Below are a number of personality characteristics. For each characteristic, please write to what extent you agree or disagree with it.
opey mentioned generated csv should generally just not be pushed to the repo, it should be regenerated every time, therefore I just removed these files.

2021-10-31 17:50 UTC, carson-ricca approved these changes
Looks ok to me if those deleted files are no longer being used.

2021-11-01 06:30 UTC, Opeyem1a commented on cluster_impressions.py
> +    cluster_survey(cluster_data, CLUSTER_CATEGORIES, 3)
All files should end with a newline

2021-11-01 06:30 UTC, Opeyem1a commented on requirements.txt
> -statsmodels==0.13.0
We don't need this requirement anymore?

2021-11-01 06:30 UTC, Opeyem1a commented on scripts/clustering/background_survey_cleaning/background_survey_cleaning.py
> +    df.index = [i for i in range(1,  len(df)+1)]  # reassign index to avoid skipping index due to missing value
Run `CTRL`+`ALT`+`L` in this file, formatting feels a tad weird

2021-11-01 06:43 UTC, MtheDV approved these changes
Will look good with opeys suggested changes

2021-11-05 00:25 UTC, MtheDV submitted a review, later dismissed

2021-11-06 22:42 UTC, Opeyem1a requested changes

2021-11-06 22:42 UTC, Opeyem1a commented on requirements.txt
> -statsmodels==0.13.0
Ayo? 😳

2021-11-07 03:51 UTC, Opeyem1a approved these changes

2021-11-07 03:51 UTC, merged