Anonymize module feedback survey
HCI-Data-Analysis/HCI-data-analysis pull request #48
Opened 2021-11-01 17:46 UTC by Opeyem1a

+ add basic script to anonymize module feedback
(Temp file added, code will be shifted into the main anonymize.py file and the documentation updated later)

2021-11-01 21:59 UTC, carson-ricca requested changes

2021-11-01 21:59 UTC, carson-ricca commented on anon.py
> +    'raw_data/341_Background_Survey_Header.csv'
How come it has the background survey file as the path? Is that just temp to ensure it was working?

2021-11-02 17:52 UTC, Opeyem1a commented on anon.py
> +    'raw_data/341_Background_Survey_Header.csv'
Yeah this is just a temp file location since Dr. Hui would have to type in the real file location

2021-11-02 18:39 UTC, carson-ricca approved these changes

2021-11-02 18:39 UTC, merged