Retrieve quiz objects
HCI-Data-Analysis/HCI-data-analysis pull request #49
Opened 2021-11-02 18:00 UTC by nononovia

2021-11-02 18:09 UTC, Opeyem1a requested changes

2021-11-02 18:09 UTC, Opeyem1a commented on quiz_onject_retrieval.py
> +from scripts import quiz_object_retrieval
Rename this file

2021-11-02 18:09 UTC, Opeyem1a commented on scripts/quiz_retrieval/quiz_retrieval.py
> +        output_path = setup_submissions_filepath(quiz, output_dir, "quiz_objects", "quiz_object" )
`"quiz_objects"` -> `"quiz"`
`"quiz_object"` -> `"quiz_id_"`

2021-11-07 04:28 UTC, nononovia commented on scripts/quiz_retrieval/quiz_retrieval.py
> +        output_path = setup_submissions_filepath(quiz, output_dir, "quiz_objects", "quiz_object" )
I don't see why this naming scheme is less confusing... Plus Bowen already ran the scripts using this naming scheme so No point changing file name, can still change the directory name I guess.

2021-11-07 21:19 UTC, carson-ricca requested changes
Looks like there are conflicts that should be resolved first.

2021-11-08 08:57 UTC, Opeyem1a commented on scripts/quiz_retrieval/quiz_retrieval.py
> +        output_path = setup_submissions_filepath(quiz, output_dir, "quiz_objects", "quiz_object" )
I made this comment in our meeting before we ran them so dw now, also it was to (a) make the directory more visually distinct from the file prefix and, more importantly, (b) make it so the filename describes what the number actually means (i.e. which field in the object the number represents)

2021-11-08 09:09 UTC, Opeyem1a requested changes

2021-11-08 09:09 UTC, Opeyem1a commented on scripts/quiz_retrieval/quiz_retrieval.py
> +def get_quiz_object(quiz_id):
Why does this function exist? We can just directly concatenate the full path with the information we already know and at best, this function can just check if a file exists at that location and raise an error if not.

There's no need to loop through every file looking for a file when we could just directly find the filepath it should be and verify

2021-11-08 09:09 UTC, Opeyem1a commented on util/canvas_api.py
> +from util import Encoder, mkdir_if_not_exists
I don't think Encoder is needed in this file

2021-11-08 09:09 UTC, Opeyem1a commented on scripts/quiz_retrieval/quiz_retrieval.py
> +def get_quiz_name(quiz_id):
Same with the comment below, why not just immediately concatenate together the full path to what the file's name should be? if `quiz_id=123456`, I can immediately look for `'.../quiz_objects/quiz_object_'+quiz_id`, then raise an error if it doesn't exist or I couldn't read it

2021-11-08 19:15 UTC, carson-ricca requested changes
I think some of the changes would require a merge with main after Mat's is merged in?

2021-11-08 19:15 UTC, carson-ricca commented on scripts/canvas_submission_retrieval/__init__.py
> +
Too many blank lines?

2021-11-08 19:15 UTC, carson-ricca commented on submission_retrieval.py
> +
I think this was removed in a different PR

2021-11-20 19:03 UTC, carson-ricca requested changes

2021-11-20 19:03 UTC, carson-ricca commented on requirements.txt
> +matplotlib==3.4.2
shows up twice

2021-11-20 19:03 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> -    course_performance_analysis('grade_book.csv', QUIZ_PATH)
Is it supposed to call the function here still?

2021-11-21 20:14 UTC, carson-ricca approved these changes

2021-11-29 01:23 UTC, closed without merging