Course performace anlysis'
HCI-Data-Analysis/HCI-data-analysis pull request #50
Opened 2021-11-05 00:23 UTC by MtheDV

2021-11-05 00:24 UTC, MtheDV commented
@nononovia lgty?

2021-11-07 21:25 UTC, carson-ricca requested changes

2021-11-07 21:25 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +import json
Main question, is there going to be another file in the root directory to run this script like the way we have done it for our other scripts?

2021-11-07 21:25 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    file = pd.read_csv(GRADEBOOK_PATH)
If we do have a file in root that runs this then the `read_csv()` should be brought into that file instead, similar to what was done with the clustering stuff.

2021-11-07 21:25 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    data448_ids = file['ID']
All of these IDs could be put in a schema instead, so we can avoid the string literals here.

2021-11-07 21:25 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    overall_pre_post_grade = 40
where does value for this constant come from?

2021-11-07 21:25 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    w_2020_retrieve_avg, w_2020_retrieve_std = 90.80, 10.5
Assuming these values had to be hardcoded?

2021-11-07 21:26 UTC, carson-ricca commented
Also conflicts should be resolved.

2021-11-08 05:35 UTC, MtheDV commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    w_2020_retrieve_avg, w_2020_retrieve_std = 90.80, 10.5
yes, they were taken from the UBC website that provided previous years grades

2021-11-08 05:36 UTC, MtheDV commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    overall_pre_post_grade = 40
the pre and post tests are both worth 20% (gradebook) of the grade, therefore we need to work with the combined total

2021-11-08 07:31 UTC, nononovia commented on scripts/course_performace_analysis/course_performace_analysis.py
> +        title='Overall Score vs First Attempt Score',
How is the first attempt reflected in this plot? To me this plot just seems like a histogram for overall course performance. The title seems a bit misleading?

2021-11-08 08:25 UTC, nononovia commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    for i in os.listdir(QUIZSCOREJSON_PATH):
What is your file structure like? Maybe create empty __init__.py files in the directories you create so your file structure is included in the repo (?

2021-11-08 09:14 UTC, Opeyem1a requested changes

2021-11-08 09:14 UTC, Opeyem1a commented on schemas/gradebook.py
> +    COMBINED_PRE_POST_WORTH = 40
This feels like a constant to be stored elsewhere and not a schema thing

2021-11-08 09:14 UTC, Opeyem1a commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    file = gradebook
I think keeping it named `gradebook` going forward makes the code more readable

2021-11-08 09:14 UTC, Opeyem1a commented on scripts/course_performace_analysis/course_performace_analysis.py
> +            number_of_quizzes += 1
I didn't review further than this, just leaving it as a marker

2021-11-08 19:20 UTC, carson-ricca requested changes

2021-11-08 19:20 UTC, carson-ricca commented on schemas/gradebook.py
> +    COMBINED_PRE_POST_WORTH = 40
Yeah this value might work better as a constant...

2021-11-08 19:20 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +                    if json_file[0]['quiz_points_possible'] > 0:
Wondering if all the ids such as `quiz_points_possible` should be in a schema or set as constants cause they seemed to be used a lot throughout the following code.

2021-11-20 15:21 UTC, nononovia commented on schemas/gradebook.py
> +    COMBINED_PRE_POST_WORTH = 40
Why do these work better as constants? They are column names just like in other schemas? (I'm probably just confused about what schemas actually do, but seems like in schema/attendance.py only constants are stored as well..?)

2021-11-20 19:00 UTC, carson-ricca commented on schemas/gradebook.py
> +    COMBINED_PRE_POST_WORTH = 40
I think for me it was just the `COMBINED_PRE_POST_WORTH` it didn't seem like a column name, but if it's a column name then it should be chill.

2021-11-20 19:01 UTC, carson-ricca submitted a review, later dismissed

2021-11-20 21:50 UTC, carson-ricca submitted a review, later dismissed
Looks good to me

2021-11-22 02:43 UTC, nononovia approved these changes

2021-11-22 05:34 UTC, Opeyem1a approved these changes

2021-11-22 05:34 UTC, merged