Distinguish quiz type
HCI-Data-Analysis/HCI-data-analysis pull request #51
Opened 2021-11-07 11:10 UTC by nononovia

2021-11-07 21:34 UTC, carson-ricca requested changes

2021-11-07 21:34 UTC, carson-ricca commented on requirements.txt
> +<<<<<<<<< Temporary merge branch 1
this looks left over :)

2021-11-07 21:34 UTC, carson-ricca commented on requirements.txt
> +seaborn==0.11.2
These look duplicated.

2021-11-07 21:34 UTC, carson-ricca commented on scripts/canvas_submission_retrieval/__init__.py
> +
Too many blank lines?

2021-11-07 21:34 UTC, carson-ricca commented on scripts/course_performace_analysis/course_performace_analysis.py
> +import json
I reviewed this in Mat's branch, so it will need to be updated once that branch gets merged with main.

2021-11-07 21:34 UTC, carson-ricca commented on submission_retrieval.py
> +    quiz_retrieval()
Not sure if this file is the best spot for this? Is the quiz retrieval directly related to submission retrieval? Otherwise, I think it should have it's own file.

2021-11-07 21:34 UTC, carson-ricca commented on scripts/quiz_retrieval/quiz_retrieval.py
> +OUTPUT_DIR = "../../data/api/canvas"
This can probably be passed as a parameter instead.

2021-11-07 21:34 UTC, carson-ricca commented on scripts/quiz_retrieval/quiz_retrieval.py
> +            file_quiz_id = quiz_object[12:18]  # the course id is the 12th to 18th character in the file name
This makes sense I wish there was a better way that didn't involve numbers though :). What's the format of the course id?

2021-11-07 21:34 UTC, carson-ricca commented on scripts/quiz_retrieval/quiz_retrieval.py
> +            file_quiz_id = quiz_object.split("_")[-1].split(".")[0]  # Extract quiz id from file name
Could it be explained a little more how this works? It's hard to tell from just looking at the code.

2021-11-08 06:00 UTC, nononovia commented on scripts/quiz_retrieval/quiz_retrieval.py
> +            file_quiz_id = quiz_object[12:18]  # the course id is the 12th to 18th character in the file name
Changed to the updated version where no numbers were involved.

2021-11-08 06:56 UTC, nononovia commented on submission_retrieval.py
> +    quiz_retrieval()
a mistake, I'm sorry

2021-11-08 06:58 UTC, nononovia commented on scripts/course_performace_analysis/course_performace_analysis.py
> +import json
Will cross that bridge when we merge that branch in main? I think this branch will probably be merged in before that one :'(

2021-11-08 19:12 UTC, carson-ricca requested changes
If all the csvs that were pushed are required in that location, then it looks much better now

2021-11-08 19:12 UTC, carson-ricca commented on web/anonymizer/anonymized/341_Background_Survey_Header.csv_anonymized.csv
> +data448id,section,section_id,submitted,attempt,3430862: Which course section are you registered in? [Grad_Section],0,"3430863: There are weekly team activities in this course. If you were to meet wit
I feel like having `.csv` twice in the filename is a little weird lol not sure if this is really an issue?

2021-11-20 17:02 UTC, nononovia commented on web/anonymizer/anonymized/341_Background_Survey_Header.csv_anonymized.csv
> +data448id,section,section_id,submitted,attempt,3430862: Which course section are you registered in? [Grad_Section],0,"3430863: There are weekly team activities in this course. If you were to meet wit
UHH, its not causing any problems and I have no idea where this come from (looks like an issue in how anonymizer creates the file name... and I am not very familiar with anonymizer...)

2021-11-20 19:06 UTC, carson-ricca submitted a review, later dismissed

2021-11-21 20:15 UTC, carson-ricca approved these changes

2021-11-29 01:23 UTC, closed without merging