Student Grouping Code
HCI-Data-Analysis/HCI-data-analysis pull request #52
Opened 2021-11-08 07:20 UTC by aadiraju

Runs student grouping and performs performance analysis per activity type using sample research questions for both impressions survey, and background survey.

2021-11-08 09:23 UTC, Opeyem1a requested changes

2021-11-08 09:23 UTC, Opeyem1a commented on scripts/student_grouping/student_grouping.py
> +    Uses the threshold value to map x onto [-1, 0, 1]
So both sides of the threshold include the threshold itself? We should put that in the docstring/report/etc

2021-11-08 09:23 UTC, Opeyem1a commented on scripts/student_grouping/student_grouping.py
> +    :param threshold: The boundaries for the neutral group: [-threshold, +threshold]
Based on the comment above's resolution, resolve this

2021-11-20 17:16 UTC, nononovia submitted a review, later dismissed
lgtm, the changes Opey mentioned seems to be resolved already?

2021-11-20 23:37 UTC, aadiraju commented
@Opeyem1a does this look good to you?

2021-11-21 02:39 UTC, aadiraju commented on scripts/student_grouping/student_grouping.py
> +    :param threshold: The boundaries for the neutral group: [-threshold, +threshold]
The set notation [] indicates inclusivity on both ends

2021-11-21 02:41 UTC, Opeyem1a approved these changes

2021-11-21 02:41 UTC, merged