Module feedback analysis
HCI-Data-Analysis/HCI-data-analysis pull request #53
Opened 2021-11-10 08:40 UTC by Opeyem1a

2021-11-10 23:28 UTC, carson-ricca requested changes
- Looks pretty good to me, just a couple of things I noticed.
- It may be a good idea to add some docstrings within the code to make it easier to understand.
- Updating the main readme with instructions on running it similar to the other scripts we have made is probably a good idea.

2021-11-10 23:28 UTC, carson-ricca commented on module_feedback_analysis.py
> +    # analyze_module_feedback(module_feedback_survey_1_df)
Should this comment be here still?

2021-11-10 23:28 UTC, carson-ricca commented on scripts/analyze_module_feedback_survey/analyze_module_feedback_survey.py
> +        # FIXME: this could be better, honestly
Definitely a little weird, could be worth looking into more?

2021-11-10 23:28 UTC, carson-ricca commented on scripts/analyze_module_feedback_survey/analyze_module_feedback_survey.py
> +    # plt.setp(plt.gca().get_xticklabels(), fontsize=10, rotation=45)
Should these comments remain?

2021-11-20 07:12 UTC, Opeyem1a commented on scripts/analyze_module_feedback_survey/analyze_module_feedback_survey.py
> +        # FIXME: this could be better, honestly
I tried to improve it but tbh I couldn't devise a better way of handling it

2021-11-20 18:59 UTC, carson-ricca approved these changes

2021-11-21 02:01 UTC, merged