Quiz performance
HCI-Data-Analysis/HCI-data-analysis pull request #54
Opened 2021-11-10 08:54 UTC by nononovia

2021-11-20 17:22 UTC, Rick-Feng-u commented on scripts/quiz_retrieval/quiz_retrieval.py
> +def download_quiz(quiz, output_filepath):
The change in quiz retrieval PR need to be merged in to this branch

2021-11-20 17:23 UTC, Rick-Feng-u requested changes
change requested

2021-11-29 05:29 UTC, Opeyem1a requested changes

2021-11-29 05:29 UTC, Opeyem1a commented on scripts/canvas_submission_retrieval/__init__.py
> +from .canvas_submission_retrieval import canvas_submission_retrieval, setup_submissions_filepath
EOF newline

2021-11-29 05:29 UTC, Opeyem1a commented on scripts/quiz_retrieval/quiz_retrieval.py
> +def get_quiz_object(quiz_id, quiz_object_path):
I'm not sure that this function name describes what this does. it also doesn't help that the docstring says it returns "the path of the quiz object" but one of the parameters is called `quiz_object_path`?

2021-11-29 05:29 UTC, Opeyem1a commented on submission_retrieval.py
> +from scripts import quiz_retrieval
why though?

2021-11-29 05:29 UTC, Opeyem1a commented on util/canvas_api.py
> +def get_quiz_id_from_file_name(file_name):
this isn't really a canvas api thing, but I see why you put it here. We can leave it for now, I just wanted to note this

2021-11-29 05:29 UTC, Opeyem1a commented on web/anonymizer/anonymized/341_Background_Survey_Header.csv_anonymized.csv
> +data448id,section,section_id,submitted,attempt,3430862: Which course section are you registered in? [Grad_Section],0,"3430863: There are weekly team activities in this course. If you were to meet wit
As much as possible, I think we should really avoid pushing changes to the data csvs as it just kinda bloats the PRs and doesn't mean anything

2021-11-29 05:29 UTC, Opeyem1a commented on scripts/course_performace_analysis/course_performace_analysis.py
> +    df_submission_type = pd.DataFrame(
I didn't really deep dive review this file since it's based on other code that already needs fixing at a later time

2021-12-06 08:11 UTC, Opeyem1a approved these changes

2021-12-06 08:12 UTC, merged