Reading Logs
HCI-Data-Analysis/HCI-data-analysis pull request #59
Opened 2021-11-20 19:06 UTC by carson-ricca

2021-11-20 19:08 UTC, carson-ricca commented on reading_logs_retrieval.py
> +    canvas_reading_logs_retrieval(EXPORT_DIR, encoder, canvas_course_id, ASSIGNMENT_IDS[0])
I understand that this looks bad lol. But every time I iterated assignments in a loop to get every attachment for every submission, after completing the first assignment the CanvasApi would timeout every time, and not allow any subsequent downloads. Running it individually for each assignment was the only way I could get it to download every assignment without API issues.

2021-11-20 19:09 UTC, carson-ricca commented on scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
> +def setup_reading_logs_filepath(parent_dir: str, sub_dir: str) -> str:
The util function in another PR will not be able to replace this due to the file extension that is part of the util function.

2021-11-20 19:11 UTC, carson-ricca commented on util/file.py
> +            os.makedirs(path)
Required to be able to make multiple directories at once.

2021-11-21 05:45 UTC, nononovia commented on reading_logs_retrieval.py
> +    canvas_reading_logs_retrieval(EXPORT_DIR, encoder, canvas_course_id, ASSIGNMENT_IDS[0])
Damn, that's unfortunate...

2021-11-21 05:48 UTC, nononovia commented on scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
> +def setup_reading_logs_filepath(parent_dir: str, sub_dir: str) -> str:
Sounds good, thank you for pointing that out.

2021-11-21 05:52 UTC, nononovia commented on scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
>      :param assignment: the assignment we are retrieving the reading logs for
the parameter assignment is removed, the docstring for assignment should probably be removed too.

2021-11-21 05:57 UTC, Rick-Feng-u approved these changes

2021-11-21 05:58 UTC, nononovia requested changes
Looks good, this seems like a rough task, and wow you came up with great solutions, thankss

2021-11-21 20:12 UTC, carson-ricca commented on scripts/canvas_reading_logs_retrieval/canvas_reading_logs_retrieval.py
>      :param assignment: the assignment we are retrieving the reading logs for
Good catch!

2021-11-22 02:38 UTC, nononovia approved these changes
lgtm

2021-11-22 02:51 UTC, merged