Parsing reading log
HCI-Data-Analysis/HCI-data-analysis pull request #64
Opened 2021-11-28 12:10 UTC by nononovia

2021-11-29 01:45 UTC, Opeyem1a reviewed
Just a quick review before I head out

2021-11-29 01:45 UTC, Opeyem1a commented on scripts/__init__.py
> +from .parse_reading_logs import parse_reading_logs
EOF newline

2021-11-29 01:45 UTC, Opeyem1a commented on scripts/parse_reading_logs/__init__.py
> +from .parse_reading_logs import parse_reading_logs
EOF newline

2021-11-29 01:45 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        # print(reading_log_path)
Remove unneeded comments from this code

2021-11-29 01:45 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +def anomolies_deletion(module: dict) -> (dict):
weird name kinda

2021-11-29 05:22 UTC, Opeyem1a requested changes

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +    module = {module_number + "-" + str(page): pd.DataFrame() for page in range(1, number_of_pages+1)}
Personally, I'm a fan of python f-strings. So instead of `'something ' + value + ' here'`
you can do `f'something {value} here'`

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +            if reading_log_folder.endswith(".json"):
Same comment about filenames. For example, I'm confused, why do we have folders that end with ".json"? Unless this variable actually means files, and if that's the case we should name it more accordingly

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +                contains_reading_log = True
So this loop sets this variable to `True` even if only 1 of the files ends in .json, right? Why keep running the loop if you've already set it to `True`?

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +            if reading_log_folder.endswith(".json"):
Also, correct me if I'm wrong, but it seems like this code runs before you even convert the .txt files to .json?

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +            parsing_reading_log_json(data448id_path, module_number, data448_id, module)
I see better why you named the files `data448_id` now, it still feels a bit weird earlier in the code though - maybe we just need some comments when you declare these variables explaining why they're named what they are?

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +                if os.path.isdir(reading_log_folder_path):
Don't nest if statements without elses, just use `and`

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +                if os.path.isdir(reading_log_folder_path):
To my understanding, this function overall checks in each student's folder and if the reading logs are right there then good, if not then aren't we just assuming that the nested folder in here is the folder containing the reading logs? Shouldn't we also be checking that this nested folder has reading logs in it?

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +    module = {module_number + "-" + str(page): pd.DataFrame() for page in range(1, number_of_pages+1)}
Naming this variable `module` also seems really undescriptive of what it actually is?

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +    convert_reading_logs_to_json(reading_log_folder_path)
yeah like if we're converting the files to .json here then why are we checking for the presence of .json files earlier than this?

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        if '(' in reading_log:  # check for duplicate files
This should use regex, doing it like this is a bit dangerous -- comment is solid because I wouldn't understand it otherwise

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        if reading_log.split('-')[0] != "COSC341":
I know these 3 `if` statements are separate for readability, but it really feels like they should just be in one conditional using `and`. If you still think separating them is worth then I understand (especially after adding regex), but the first and last ones should be combined imo

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +            reading_log_dict['end_time'] = reading_log_json['endTime']
this line should be done at the same point as line 80, you know the information back then so doing it there makes sense

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        module[mod_num_page_num] = module[mod_num_page_num].append(reading_log_series)
Idk if it's the variable names or the logic, but I have no idea what line 91 does

2021-11-29 05:22 UTC, Opeyem1a commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        # if more than half of the data in a column is NA, drop the column
But why half? Like I'm confused as to why 50% is the threshold for this?

2021-11-29 06:32 UTC, Rick-Feng-u commented on scripts/parse_reading_logs/parse_reading_logs.py
> +def anomolies_deletion(module: dict) -> (dict):
They are anomalies because they do not belong in the data frame

2021-11-29 06:34 UTC, Rick-Feng-u commented on scripts/parse_reading_logs/parse_reading_logs.py
> +    for data448_id in os.listdir(module_path):
yes, because the folder name that contains all the reading log files are data448 id

2021-11-29 06:34 UTC, Rick-Feng-u commented on scripts/parse_reading_logs/parse_reading_logs.py
> +    for data448_id in os.listdir(module_path):
and all the variable that we given name in all the for loop are the name of the folder

2021-11-29 07:34 UTC, nononovia commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        if '(' in reading_log:  # check for duplicate files
no regex pls

2021-11-29 07:56 UTC, nononovia commented on scripts/parse_reading_logs/parse_reading_logs.py
> +        # if more than half of the data in a column is NA, drop the column
Technically, 5 or some small number should be satisfactory since not that many students hand in abnormal files. However, generally speaking, if less than half of the student did not complete a page, maybe that page should be discarded anyways?

2021-12-06 08:30 UTC, Opeyem1a approved these changes

2021-12-06 08:32 UTC, Opeyem1a approved these changes

2021-12-06 08:32 UTC, merged