Reading Logs Completion Time Comparision
HCI-Data-Analysis/HCI-data-analysis pull request #65
Opened 2021-11-29 00:06 UTC by carson-ricca

- Currently I noticed that there may be an issue when the folders have subdirectories, the reading logs in subdirectories are not currently being counted. This needs to be fixed, which may change the average completion time, but I don't think it would be that drastic.

2022-01-10 21:44 UTC, carson-ricca commented
Currently requires Opey's PR to be merged so I can then implement the util functions properly.

2022-01-18 03:08 UTC, Opeyem1a requested changes

2022-01-18 03:08 UTC, Opeyem1a commented on reading_logs_completion.py
> +READING_TIMES = [100, 40, 45, 60, 65, 45, 60, 60, 25, 1, 25, 50]
These are the expected ones, right? Maybe just naming the variable that might be more clear

2022-01-18 03:08 UTC, Opeyem1a commented on scripts/reading_logs/reading_logs_completion_time.py
> +        print(i)
print()?

2022-01-18 03:08 UTC, Opeyem1a commented on scripts/reading_logs/reading_logs_completion_time.py
> +    for i in range(12):
Is 12 just the number of modules? I think we should loop through the schema constant instead?

2022-01-18 03:08 UTC, Opeyem1a commented on scripts/reading_logs/reading_logs_completion_time.py
> +    average_completion_times = []
Is this a good variable name? I can't think of a better one so it is what it is

2022-01-18 03:08 UTC, Opeyem1a commented on util/reading_logs.py
> +        return mean_and_sd(page_durations, False)
I think we should have this boolean also be in the `module_reading_duration()` function, since people might want this function to return the average

2022-01-18 03:08 UTC, Opeyem1a commented on util/reading_logs.py
> +def mean_and_sd(values: [], mean=True) -> (float, float):
I think we should rename this function to `aggregate_and_sd()` if we give the option for it to not be the mean

2022-01-18 03:08 UTC, Opeyem1a commented on util/reading_logs.py
> +        return sum(values_list), sd
Is graphed error still supposed to be the sd if it's the sum? Might be a question for Bowen

2022-01-18 19:32 UTC, carson-ricca commented on scripts/reading_logs/reading_logs_completion_time.py
> +    for i in range(12):
Yeah, it's just the number of modules.

2022-01-18 19:32 UTC, carson-ricca commented on scripts/reading_logs/reading_logs_completion_time.py
> +    average_completion_times = []
I also could not think of something better.

2022-01-23 05:16 UTC, MtheDV approved these changes

2022-01-27 01:14 UTC, Opeyem1a approved these changes

2022-01-27 02:07 UTC, merged