Complete Reading Logs Utils + Restructuring
HCI-Data-Analysis/HCI-data-analysis pull request #78
Opened 2021-12-06 10:27 UTC by Opeyem1a

+ complete reading log duration util functions
+ they use real data now lads
+ all reading logs related scripts should go in `scripts/reading_logs` I think

Closes #77

2021-12-06 18:53 UTC, carson-ricca requested changes
Looks good overall, how is the cleaned reading log data being used? Is it being uploaded manually into the data folder when you want to run stuff related to reading logs?

2021-12-06 18:53 UTC, carson-ricca commented on util/reading_logs.py
> +            start_time = reading_duration_df['start_time'][f'{data448_id}']
The data frame ids could be constant since they are being used more than once?

2021-12-06 23:03 UTC, Opeyem1a commented on util/reading_logs.py
> +            start_time = reading_duration_df['start_time'][f'{data448_id}']
Like the `'start_time'` should be a constant in this function?

2021-12-06 23:05 UTC, Opeyem1a commented
The cleaned reading logs get uploaded to `data/api/canvas/reading_logs` and then `parse_reading_logs.py` will create the dictionaries of dataframes and save the binary for them in `.pkl` files stored in `data/cache`. Then `ReadingLogsData` just reads those `.pkl` files.

2021-12-07 02:57 UTC, carson-ricca commented on util/reading_logs.py
> +            start_time = reading_duration_df['start_time'][f'{data448_id}']
Yeah, that's what I was thinking, not necessary but just wanted your thoughts on it?

2021-12-07 02:58 UTC, carson-ricca commented
Above comment and conflicts now

2021-12-07 02:59 UTC, carson-ricca requested changes
Above comment and conflicts now

2022-01-13 19:08 UTC, carson-ricca approved these changes
LGTM now.

2022-01-15 00:03 UTC, MtheDV approved these changes

2022-01-15 00:06 UTC, merged