Average paragraph reading speed and pre-test reading behaviour analyis'
HCI-Data-Analysis/HCI-data-analysis pull request #87
Opened 2022-01-27 22:39 UTC by MtheDV

Create functions to perform analysis' on average paragraph reading speed and pre-test reading behaviour.

Closes #86

2022-02-10 15:49 UTC, Opeyem1a requested changes

2022-02-10 15:52 UTC, Opeyem1a requested changes

2022-02-10 15:52 UTC, Opeyem1a commented on scripts/__init__.py
> +from .average_module_paragraph_reading_speed import graph_average_module_paragraph_reading_speed
If not needed, remove

2022-02-10 15:52 UTC, Opeyem1a commented on scripts/average_module_paragraph_reading_speed/average_module_paragraph_reading_speed.py
> +    g.set_axis_labels("Difficulty (100-Flesch)", "Content Quiz Performance (Extra attempts)")
"Extra attempts" -> "Extra attempt ratio"
In each case, too

2022-02-11 00:01 UTC, MtheDV commented on average_module_paragraph_reading_speed.py
> +    graph_average_module_paragraph_reading_speed(MODULE_DIFFICULTY_LENGTH_FILEPATH)
Yes this is for one of my sections

2022-02-11 02:06 UTC, Opeyem1a approved these changes

2022-02-11 02:08 UTC, merged